### ISSUE TITLE
Powerloss Macro consume 99%+ of moonraker

### ISSUE THREAD

**Issue by Salobaka** [CODeRUS/klipper_config#1]
Using this macros at"Before layer change G-code" or "After layer change G-code" make mooraker crazy and consume 99% on load. This 99% load affect to stable working web UI. 

I try to comment non-prioritise metrics and stay only important to resume, but it still very heavy script. 
How i can make it a little lightweight?

My macros here: https://pastebin.com/CtDxSDPz

**Comment by CODeRUS** [comment]
just move save_variables file out of config dir, e.g: 
```
[save_variables]
filename: ~/printer_data/variables.cfg
```

**Comment by Salobaka** [comment]
Not helping. At one pronter - helps. At another - not. What it can be?
<img width="438" alt="image" src="https://user-images.githubusercontent.com/5549100/235268805-1f2c34b7-1c23-41e6-b9a8-2fba63e9bf63.png">

**Comment by CODeRUS** [comment]
check moonraker logs, i cannot reproduce
