### ISSUE TITLE
Make possible to comment low priority values

### ISSUE THREAD

**Issue by Salobaka** [CODeRUS/klipper_config#2]
!! Error on 'SET_PRESSURE_ADVANCE ADVANCE= SMOOTH_TIME=': unable to parse

Please make possible to comment values that dont required to resumen printing:
- pl_pressure_advance
- pl_smooth_time
- pl_retract_length
- pl_retract_speed
- pl_unretract_speed
- pl_velocity
- pl_accel
- pl_accel_to_decel
- pl_sqv

all this values has optimal default values and set to defult after power loss. 
But temp, and coordinates are critical to resuming.

**Comment by CODeRUS** [comment]
no
