### ISSUE TITLE
code_macro POWER_LOSS_SAVE - klipper.0.11 - no attribute 'firmware_retraction'

### ISSUE THREAD

**Issue by Salobaka** [CODeRUS/klipper_config#3]
1:59:08 
!! Error evaluating 'gcode_macro POWER_LOSS_SAVE:gcode': jinja2.exceptions.UndefinedError: 'extras.gcode_macro.GetStatusWrapper object' has no attribute 'firmware_retraction'

**Comment by CODeRUS** [comment]
add fw retract to your config

**Comment by Salobaka** [comment]
Thanks.
