### ISSUE TITLE
M23 didn't executing - Maybe something with filename format?

### ISSUE THREAD

**Issue by Salobaka** [CODeRUS/klipper_config#4]
[power_loss_simple]
Detected unfinished print: 575.gcode
14:24:30 type POWER_LOSS_RECOVERY to continue printing
14:24:30 or POWER_LOSS_CLEAR to drop it
14:24:41 $ POWER_LOSS_RECOVERY
14:24:41 [power_loss_simple] Restoring print after power loss
14:24:41 
Begin file list
14:24:41 575.gcode 26052199
14:24:42 5751.GCODE 26052199
End file list
14:24:42 SD card ok
14:24:42  // Unknown command:"M23 575."

**Comment by CODeRUS** [comment]
works for me. check contents of power_loss_save variable
